layout: test
title: "test page"
permalink: /test
filename: test.md

layout: alcx
title: "ALCX Twitter"
permalink: /alcx_twitter
filename: alcx_twitter.md

layout: alcx
title: "ALCX Inequality"
permalink: /alcx_gini
filename: alcx_gini.md 

layout: alcx
title: "ALCX Investors"
permalink: /alcx_early
filename: alcx_early.md

layout: alcx
title: "ALCX Users"
permalink: /alcx_active
filename: alcx_active.md

layout: alcx
title: "ALCX Fork"
permalink: /alcx_fork
filename: alcx_fork.md

layout: alcx
title: "ALCX Users"
permalink: /alcx_users
filename: alcx_users.md

theme: jekyll-theme-minimal
