layout: test
title: "test page"
permalink: /test
filename: test.md
layout: alcx
title: "ALCX Twitter"
permalink: /alcx_twitter
filename: alcx_twitter.md
layout: alcx
title: "ALCX Holders"
permalink: /alcx_gini
filename: alcx_gini.md
theme: jekyll-theme-minimal
